// src/views/LoginView.tsx
import React, { useState, FormEvent } from 'react';
import { InputText } from 'primereact/inputtext';
import { Password } from 'primereact/password';
import { Button } from 'primereact/button';
import { Card } from 'primereact/card';
import { Message } from 'primereact/message';
import { useNavigate, Link } from 'react-router-dom';
import { useAuthStore } from '../store/authStore';

const LoginView: React.FC = () => {
  const [username, setUsername] = useState<string>('');
  const [password, setPassword] = useState<string>('');
  const [error, setError] = useState<string>('');
  const [loading, setLoading] = useState<boolean>(false);

  const login = useAuthStore((state) => state.login);
  const navigate = useNavigate();

  const handleLogin = async (e: FormEvent) => {
    e.preventDefault();
    setLoading(true);
    setError('');

    try {
      await login(username, password);
      navigate('/');
    } catch {
      setError('Неверное имя пользователя или пароль');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="flex align-items-center justify-content-center" style={{ minHeight: '100vh' }}>
      <Card title="Вход в систему" style={{ width: '100%', maxWidth: '400px' }}>
        <form onSubmit={handleLogin} className="flex flex-column gap-3">
          <div className="flex flex-column gap-2">
            <label htmlFor="username">Логин</label>
            <InputText
              id="username"
              value={username}
              onChange={(e: React.ChangeEvent<HTMLInputElement>) => setUsername(e.target.value)}
              required
            />
          </div>
          <div className="flex flex-column gap-2 w-full">
            <label htmlFor="password">Пароль</label>
            <Password
              id="password"
              value={password}
              onChange={(e: React.ChangeEvent<HTMLInputElement>) => setPassword(e.target.value)}
              toggleMask
              feedback={false}
              className="w-full"
              inputClassName="w-full"
              required
            />
          </div>
          {error && <Message severity="error" text={error} />}
          <Button label="Войти" icon="pi pi-sign-in" loading={loading} type="submit" />
          <div className="text-center mt-2">
            Нет аккаунта? <Link to="/register">Зарегистрироваться</Link>
          </div>
        </form>
      </Card>
    </div>
  );
};

export default LoginView;

// src/views/LoginView.vue
<script setup>
import { ref } from 'vue';
import { useAuthStore } from '../stores/auth';
import Card from 'primevue/card';
import InputText from 'primevue/inputtext';
import Password from 'primevue/password';
import Button from 'primevue/button';
import Message from 'primevue/message';

const authStore = useAuthStore();
const isLogin = ref(true);
const username = ref('');
const password = ref('');
const error = ref('');

const submit = async () => {
    error.value = '';
    try {
        if (isLogin.value) {
            await authStore.login(username.value, password.value);
        } else {
            await authStore.register(username.value, password.value);
        }
    } catch (e) {
        error.value = e;
    }
};
</script>

<template>
    <div class="flex-center">
        <Card style="width: 25rem; overflow: hidden">
            <template #title>{{ isLogin ? 'Вход' : 'Регистрация' }}</template>
            <template #content>
                <div class="flex flex-col gap-4">
                    <div class="flex flex-col gap-2">
                        <label for="username">Имя пользователя</label>
                        <InputText id="username" v-model="username" />
                    </div>
                    <div class="flex flex-col gap-2">
                        <label for="password">Пароль</label>
                        <Password id="password" v-model="password" :feedback="false" toggleMask fluid />
                    </div>
                    <Message v-if="error" severity="error">{{ error }}</Message>
                </div>
            </template>
            <template #footer>
                <div class="flex gap-4 mt-1">
                    <Button :label="isLogin ? 'Войти' : 'Создать аккаунт'" class="w-full" @click="submit" />
                    <Button :label="isLogin ? 'Нет аккаунта?' : 'Уже есть аккаунт?'" link class="w-full"
                        @click="isLogin = !isLogin; error = ''" />
                </div>
            </template>
        </Card>
    </div>
</template>

<style scoped>
.flex-center {
    display: flex;
    justify-content: center;
    align-items: center;
    height: 100vh;
    background-color: #f4f4f9;
}

.flex-col {
    display: flex;
    flex-direction: column;
}

.gap-4 {
    gap: 1rem;
}

.gap-2 {
    gap: 0.5rem;
}

.w-full {
    width: 100%;
}
</style>
